### ISSUE TITLE
Enter and Backspace Do Not Work

### ISSUE THREAD

**Issue by DarwinJS** [neilsustc/vscode-markdown#290]
#### What is the problem?
Enter and Backspace stop working in Markdown.
It happens even if the preview window is not up.
I have not had it affect other keys.
It is not consistent - currently it is there most of the time - but sometimes it just magically starts working.
I've had this problem many times through many versions of Markdown-All-In-One
When I uninstall it the problem goes away.

Markdown all in one version: 1.6.2
VS code versions:
Version: 1.27.2 (system setup)
Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
Date: 2018-09-12T16:17:45.060Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

#### How can I reproduce it?
Load a markdown file and press enter - nothing happens.
Press backspace - nothing happens.

#### Is there any error message in the console?

[2018-10-03 06:49:17.368] [renderer1] [info] standard startup {"version":"1.27.2","ellapsed":3543,"isLatestVersion":true,"didUseCachedData":true,"windowKind":1,"windowCount":1,"viewletId":"workbench.view.explorer","editorIds":["workbench.editors.files.fileEditorInput"],"timers":{"ellapsedAppReady":155,"ellapsedNlsGeneration":0,"ellapsedWindowLoad":583,"ellapsedWindowLoadToRequire":826,"ellapsedRequire":964,"ellapsedExtensions":1789,"ellapsedEditorRestore":788,"ellapsedViewletRestore":39,"ellapsedPanelRestore":0,"ellapsedWorkbench":985,"ellapsedExtensionsReady":4355,"ellapsedTimersToTimersComputed":236},"platform":"win32","release":"10.0.17134","arch":"x64","totalmem":17057910784,"freemem":4356005888,"meminfo":{"workingSetSize":204196,"peakWorkingSetSize":204196,"privateBytes":186324,"sharedBytes":40276},"cpus":{"count":8,"speed":2394,"model":"Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz"},"loadavg":[0,0,0],"initialStartup":true,"isVMLikelyhood":0,"hasAccessibilitySupport":false,"emptyWorkbench":false,"common.machineId":"7dc159cb67866caa057e36783a8e5a5b3f1a76dd245aa24c737997196e21384b","sessionID":"e6f18ebc-5f76-4661-bb08-5f053706f8711538563755250","commitHash":"f46c4c469d6e6d8c46f268d1553c5dc4b475840f","common.platformVersion":"10.0.17134","common.platform":"Windows","common.nodePlatform":"win32","common.nodeArch":"x64","timestamp":"2018-10-03T10:49:17.368Z","common.timesincesessionstart":2118,"common.sequence":9,"common.version.shell":"2.0.7","common.version.renderer":"61.0.3163.100","common.firstSessionDate":"Wed, 16 Sep 2015 15:40:06 GMT","common.lastSessionDate":"Wed, 03 Oct 2018 10:47:22 GMT","common.isNewSession":"0","common.instanceId":"d5a6779e-4c4c-428f-a14f-30ab26e229e0"}
[2018-10-03 06:49:36.165] [renderer1] [error] Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
	at loadTocConfig (C:\Users\sanoyd\.vscode\extensions\yzhang.markdown-all-in-one-1.6.0\out\src\toc.js:208:34)
	at C:\Users\sanoyd\.vscode\extensions\yzhang.markdown-all-in-one-1.6.0\out\src\toc.js:63:9
	at Generator.next (<anonymous>)
	at C:\Users\sanoyd\.vscode\extensions\yzhang.markdown-all-in-one-1.6.0\out\src\toc.js:7:71
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\sanoyd\.vscode\extensions\yzhang.markdown-all-in-one-1.6.0\out\src\toc.js:3:12)
	at generateTocText (C:\Users\sanoyd\.vscode\extensions\yzhang.markdown-all-in-one-1.6.0\out\src\toc.js:62:12)
	at C:\Users\sanoyd\.vscode\extensions\yzhang.markdown-all-in-one-1.6.0\out\src\toc.js:104:32
	at Generator.next (<anonymous>)
	at C:\Users\sanoyd\.vscode\extensions\yzhang.markdown-all-in-one-1.6.0\out\src\toc.js:7:71
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\sanoyd\.vscode\extensions\yzhang.markdown-all-in-one-1.6.0\out\src\toc.js:3:12)
	at detectTocRange (C:\Users\sanoyd\.vscode\extensions\yzhang.markdown-all-in-one-1.6.0\out\src\toc.js:103:12)
	at TocCodeLensProvider.provideCodeLenses (C:\Users\sanoyd\.vscode\extensions\yzhang.markdown-all-in-one-1.6.0\out\src\toc.js:240:16)
	at c:\Program Files\Microsoft VS Code\_\resources\app\out\vs\workbench\node\extensionHostProcess.js:747:434
	at c:\Program Files\Microsoft VS Code\_\resources\app\out\vs\workbench\node\extensionHostProcess.js:108:466
	at new n.Class.derive._oncancel (c:\Program Files\Microsoft VS Code\_\resources\app\out\vs\workbench\node\extensionHostProcess.js:86:460)
	at Object.t.asWinJsPromise (c:\Program Files\Microsoft VS Code\_\resources\app\out\vs\workbench\node\extensionHostProcess.js:108:431)
	at e.provideCodeLenses (c:\Program Files\Microsoft VS Code\_\resources\app\out\vs\workbench\node\extensionHostProcess.js:747:388)
	at c:\Program Files\Microsoft VS Code\_\resources\app\out\vs\workbench\node\extensionHostProcess.js:762:213
	at e._withAdapter (c:\Program Files\Microsoft VS Code\_\resources\app\out\vs\workbench\node\extensionHostProcess.js:761:91)
	at e.$provideCodeLenses (c:\Program Files\Microsoft VS Code\_\resources\app\out\vs\workbench\node\extensionHostProcess.js:762:175)
	at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\_\resources\app\out\vs\workbench\node\extensionHostProcess.js:681:309)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\_\resources\app\out\vs\workbench\node\extensionHostProcess.js:681:27)
	at e._receiveRequest (c:\Program Files\Microsoft VS Code\_\resources\app\out\vs\workbench\node\extensionHostProcess.js:679:802)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\_\resources\app\out\vs\workbench\node\extensionHostProcess.js:678:993)
	at c:\Program Files\Microsoft VS Code\_\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:791
	at c:\Program Files\Microsoft VS Code\_\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:597
	at e.fire (c:\Program Files\Microsoft VS Code\_\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:917)
	at a (c:\Program Files\Microsoft VS Code\_\resources\app\out\vs\workbench\node\extensionHostProcess.js:164:787)
	at Socket._socketDataListener (c:\Program Files\Microsoft VS Code\_\resources\app\out\vs\workbench\node\extensionHostProcess.js:164:1006)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)

**Comment by neilsustc** [comment]
I see the error `Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined`

It is weird since this extension tries getting your active editor and then accessing `editor.document`.

Could you please disable all other extensions except for this one and test again?

![image](https://user-images.githubusercontent.com/7588612/46409867-eaf20800-c70e-11e8-959e-e19a571ed62a.png)

**Comment by DarwinJS** [comment]
Ok - disabling all did make it work correctly - so it must be another extension.
I will reenable them bit by bit and remove any I don't use anymore.

Thanks!
