### ISSUE TITLE
Error: Cannot read property '1' of null

### ISSUE THREAD

**Issue by alxmcr** [neilsustc/vscode-markdown#299]
#### Settings

Versión: 1.28.0 (user setup)
Confirmación: 431ef9da3cf88a7e164f9d33bf62695e07c6c2a9
Fecha: 2018-10-05T14:58:53.203Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Arquitectura: x64

#### What is the problem?

Error: Cannot read property '1' of null

#### How can I reproduce it?

1. (Windows) Press F1 > Create Table Contents of Contents

#### Is there any error message in the console?

```
Cannot read property '1' of null
```

![image](https://user-images.githubusercontent.com/8689897/46772466-215af480-ccc6-11e8-8772-5c762f8fab9e.png)

**Chrome Dev Tools**

![image](https://user-images.githubusercontent.com/8689897/46772326-819d6680-ccc5-11e8-9b77-b0bebffaa68c.png)

```
notificationsAlerts.ts:40 Error: Cannot read property '1' of null
	at editor.document.getText.split.filter.map.lineText (C:\Users\PC_INVADER\.vscode\extensions\yzhang.markdown-all-in-one-1.6.2\out\src\toc.js:223:37)
	at Array.map (<anonymous>)
	at buildToc (C:\Users\PC_INVADER\.vscode\extensions\yzhang.markdown-all-in-one-1.6.2\out\src\toc.js:220:14)
	at C:\Users\PC_INVADER\.vscode\extensions\yzhang.markdown-all-in-one-1.6.2\out\src\toc.js:61:26
	at Generator.next (<anonymous>)
	at C:\Users\PC_INVADER\.vscode\extensions\yzhang.markdown-all-in-one-1.6.2\out\src\toc.js:7:71
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\PC_INVADER\.vscode\extensions\yzhang.markdown-all-in-one-1.6.2\out\src\toc.js:3:12)
	at generateTocText (C:\Users\PC_INVADER\.vscode\extensions\yzhang.markdown-all-in-one-1.6.2\out\src\toc.js:57:12)
	at C:\Users\PC_INVADER\.vscode\extensions\yzhang.markdown-all-in-one-1.6.2\out\src\toc.js:25:25
	at Generator.next (<anonymous>)
	at C:\Users\PC_INVADER\.vscode\extensions\yzhang.markdown-all-in-one-1.6.2\out\src\toc.js:7:71
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\PC_INVADER\.vscode\extensions\yzhang.markdown-all-in-one-1.6.2\out\src\toc.js:3:12)
	at createToc (C:\Users\PC_INVADER\.vscode\extensions\yzhang.markdown-all-in-one-1.6.2\out\src\toc.js:23:12)
	at e._executeContributedCommand (c:\Users\PC_INVADER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:452:706)
	at e.$executeContributedCommand (c:\Users\PC_INVADER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:453:212)
	at t._doInvokeHandler (c:\Users\PC_INVADER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:640:888)
	at t._invokeHandler (c:\Users\PC_INVADER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:640:554)
	at t._receiveRequest (c:\Users\PC_INVADER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:639:126)
	at t._receiveOneMessage (c:\Users\PC_INVADER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:638:59)
	at c:\Users\PC_INVADER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:926
	at c:\Users\PC_INVADER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:138
	at e.fire (c:\Users\PC_INVADER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:496)
	at a (c:\Users\PC_INVADER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:213)
	at Socket._socketDataListener (c:\Users\PC_INVADER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:432)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
t.onDidNotificationChange @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:28
e.fire @ event.ts:140
t.notify @ notifications.ts:115
t.error @ notificationService.ts:50
t.onError @ commandsHandler.ts:328
(anonymous) @ commandsHandler.ts:313
m @ winjs.base.js:1230
enter @ winjs.base.js:916
_run @ winjs.base.js:1089
_error @ winjs.base.js:1062
e.resolveErr @ lazyPromise.ts:72
t._receiveReplyErr @ rpcProtocol.ts:422
t._receiveOneMessage @ rpcProtocol.ts:319
(anonymous) @ rpcProtocol.ts:149
e.fire @ event.ts:140
a @ ipc.net.ts:105
n._socketDataListener @ ipc.net.ts:134
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594
```

Please, I'll appreciate your help.

**Comment by neilsustc** [comment]
Please refer to [this comment](https://github.com/neilsustc/vscode-markdown/issues/275#issuecomment-428255125).

I guess you have the similar issue which is cause by code blocks. Otherwise more details are needed since it is not reproducable in most text.

**Comment by alxmcr** [comment]
> Please refer to [this comment](https://github.com/neilsustc/vscode-markdown/issues/275#issuecomment-428255125).
> 
> I guess you have the similar issue which is cause by code blocks. Otherwise more details are needed since it is not reproducable in most text.

Hi @neilsustc , Thanks for answering! I'm so sorry. My Markdown file is [File.md](https://gist.github.com/alxmcr/6b3ea849e3fc823cfea1e09a5cb5ae69)

When I want to **create a Table Contents of Contents** from Line 20, I get this error message: **"Error: Cannot read property '1' of null"**. 

Please, can you help me? I'll appreciate it.

**Comment by alxmcr** [comment]
> Actually, the fix was provided several posts behind that comment...
> 
> Anyway, you can download and install the latest dev/CI build which includes the fix. This time please find it by yourself 😉. (hint: at the end of the `README`)

Thanks for answering! The problem was **resolved**. I downloaded and installed the **latest dev/CI version**. Here is the file [Download](https://ci.appveyor.com/project/neilsustc/vscode-markdown/build/artifacts). Thanks again!
