### ISSUE TITLE
Errors showing when VSCode opening

### ISSUE THREAD

**Issue by eramdam** [neilsustc/vscode-markdown#37]
It seems like the last update is triggering an error whenever VSCode is opened or when I open a file. 
Here are the stacktraces:
<details>
<pre>
messageService.ts:125 Cannot read property 'filter' of null: TypeError: Cannot read property 'filter' of null
	at MdOutlineProvider.getChildren (/Users/Damien/.vscode/extensions/yzhang.markdown-all-in-one-0.10.1/out/src/toc.js:242:28)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:257200
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:63276
	at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:48394)
	at Object.t.asWinJsPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:63239)
	at t.getTreeItems (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:257152)
	at e.$getElements (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:256203)
	at t.e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:423958)
	at e._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:280554)
	at e._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:280244)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:279271
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:281190
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:56058
	at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:55287)
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:57078)
	at Socket.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:102495)
e.doShow	@	messageService.ts:125
e.show	@	messageService.ts:104
(anonymous)	@	mainThreadTreeViews.ts:71
v	@	winjs.base.raw.js:1209
enter	@	winjs.base.raw.js:901
_run	@	winjs.base.raw.js:1068
_error	@	winjs.base.raw.js:1041
e.resolveErr	@	lazyPromise.ts:77
e._receiveOneMessage	@	rpcProtocol.ts:68
(anonymous)	@	rpcProtocol.ts:32
(anonymous)	@	rpcProtocol.ts:157
e.invoke	@	callbackList.ts:63
e.fire	@	event.ts:123
(anonymous)	@	ipc.net.ts:82
emitOne	@	events.js:96
emit	@	events.js:191
readableAddChunk	@	_stream_readable.js:178
Readable.push	@	_stream_readable.js:136
onread	@	net.js:560
</pre>
</details>
<details>
<pre>
Please return an array of children.: Error: Please return an array of children.
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:204908
    at Object.g [as _notify] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:52522)
    at Object.enter (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:56594)
    at n.Class.derive._oncancel._run (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:57915)
    at n.Class.derive._oncancel._error (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:57432)
    at e.resolveErr (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:2434911)
    at e._receiveOneMessage (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:2436272)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:2435600
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:2437519
    at e.invoke (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:66905)
e.onUnexpectedError @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29
</pre>
</details>

I know how frustrating it can be to get an error report just after a release 😅 Keep up the good work on the extension though! ❤️

**Comment by neilsustc** [comment]
Thanks for your report. I'll have a look

**Comment by neilsustc** [comment]
I believe it is fixed in v0.10.2 😉

**Comment by eramdam** [comment]
@neilsustc Indeed! Thanks for the quick fix 😄
