### ISSUE TITLE
Format Table fails to format tables with alignment

### ISSUE THREAD

**Issue by jonasbb** [neilsustc/vscode-markdown#66]
Affected Version: 0.11.2

Formatting a table like

```markdown
|a|b|
|--:|---|
|1|2|
```

fails and only produces an error message. Using `:` for left/right/center alignment is supported by GFM tables.

The error message is only shown in the console log.

```text
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:10 Cannot read property 'forEach' of null: TypeError: Cannot read property 'forEach' of null
	at MarkdownDocumentFormatter.provideDocumentFormattingEdits (/home/jbushart/.vscode/extensions/yzhang.markdown-all-in-one-0.11.2/out/src/tableFormatter.js:15:15)
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:437723
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:92953
	at new n.Class.derive._oncancel (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:72291)
	at Object.t.asWinJsPromise (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:92916)
	at e.provideDocumentFormattingEdits (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:437677)
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:449093
	at e._withAdapter (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:445314)
	at e.$provideDocumentFormattingEdits (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:449055)
	at t.e.invoke (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:509443)
```

**Comment by neilsustc** [comment]
I would suggest using at least 3 hyphens `-` (that says `---:` rather then `--:`)
